export const rows = [
  {
    id: 1,
    name: "Walter White",
    email: "heisenberg@gmail.com",
    age: 52,
    phone: "(665)121-5454",
    access: "Admin",
  },
  {
    id: 2,
    name: "Jesse Pinkman",
    email: "jessepinkman@gmail.com",
    age: 31,
    phone: "(421)314-2288",
    access: "Admin",
  },
  {
    id: 3,
    name: "Mike Ehrmantraut",
    email: "mikeehrmantraut@gmail.com",
    age: 66,
    phone: "(422)982-6739",
    access: "Admin",
  },
  {
    id: 4,
    name: "Saul Goodman",
    email: "saulgoodman@gmail.com",
    age: 49,
    phone: "(921)425-6742",
    access: "Manager",
  },
  {
    id: 5,
    name: "Hank Schrader",
    email: "hankschrader@gmail.com",
    age: 45,
    phone: "(421)445-1189",
    access: "Manager",
  },
  {
    id: 6,
    name: "Skyler White",
    email: "skylerwhite@gmail.com",
    age: 43,
    phone: "(232)545-6483",
    access: "User",
  },
  {
    id: 7,
    name: "Jane Margolis",
    email: "janemargolis@gmail.com",
    age: 27,
    phone: "(543)124-0123",
    access: "User",
  },
  {
    id: 8,
    name: "Hector Salamanca",
    email: "hectorsalamanca@gmail.com",
    age: 79,
    phone: "(222)444-5555",
    access: "User",
  },
  {
    id: 9,
    name: "Gus Fring",
    email: "gusfring@gmail.com",
    age: 65,
    phone: "(444)555-6239",
    access: "User",
  },
];
